{{- if .Values.agent.overlayDns.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-overlay-dns" (include "heteronetwork.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "heteronetwork.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  records.json: |
    {{ dict "schema_version" 1 "records" .Values.agent.overlayDns.records "gateway_records" .Values.agent.overlayDns.gatewayRecords | toPrettyJson | nindent 4 }}
{{- end }}
