{{- if eq (printf "%v" .Values.serviceAccount.create) "true" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipars.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "ipars.name" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
