{{- include "ipars.validateBoolean" (dict "path" "serviceAccount.create" "value" .Values.serviceAccount.create) -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipars.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "ipars.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
