fullnameOverride: heterocloud-flash-dev
api:
  replicaCount: 3
controller:
  replicaCount: 2
publicDomain: flash.${domain}
workloadNamespace: heterocloud-flash-dev-workloads
runtimeClass:
  create: false
  name: gvisor
persistence:
  enabled: true
  storageClass: ${flash_storage_class}
adminVolumeClaims: []
adminVolumeMounts: {}
providerAuth:
  issuer: heterocloud-dev
  audience: heterocloud-flash-dev
  existingSecret: heterocloud-flash-dev-provider-auth
  publicKeysJson: ""
registry:
  enabled: false
nodeSelector: {}
