apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: postgres-ha-connector
    namespace: kube-system
    files:
      - haproxy.cfg=postgres-haproxy.cfg

resources:
  - coredns.yaml
  - nodelocaldns.yaml
  - postgres-ha-connector.yaml
  - service-route.yaml
