apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: hetero-platform
  source:
    repoURL: git://10.250.0.2:19419/heteronetwork-infrastructure.git
    targetRevision: master
    path: deploy/gitops/cluster-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: heteronetwork-overlay-dns-effective
      namespace: kube-system
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
