apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-s3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: hetero-platform
  source:
    repoURL: https://yandex-cloud.github.io/k8s-csi-s3/charts
    chart: csi-s3
    targetRevision: 0.43.7
    helm:
      releaseName: csi-s3
      values: |
        secret:
          create: false
          name: escape-syouyu-csi
        storageClass:
          create: true
          name: syouyu-flash-escape
          singleBucket: escape-019fbda8-persistent
          mounter: geesefs
          mountOptions: "--memory-limit 2048 --dir-mode 0700 --file-mode 0600"
          reclaimPolicy: Retain
        tolerations:
          all: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
