apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heterocloud-flash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: hetero-platform
  source:
    repoURL: https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud-Flash.git
    targetRevision: v0.1.21
    path: deploy/helm/heterocloud-flash
    helm:
      releaseName: heterocloud-flash
      values: |
        image:
          tag: 0.1.21
        persistence:
          enabled: true
          storageClass: longhorn-static
        adminVolumeClaims:
          - name: escape-syouyu-workspace
            storageClass: syouyu-flash-escape
            size: 10Gi
        adminVolumeMounts:
          "01a05ad9-b529-7573-ad27-e7fe1fb447e3":
            - name: syouyu-workspace
              claimName: escape-syouyu-workspace
              mountPath: /root/syouyu
              readOnly: false
        providerAuth:
          publicKeysJson: |-
            {"heterocloud-provider-1":"-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAs9HXnx9AwepDSdl/w+k2tAYieW3aU8PhlJoQBAFo9X4=\n-----END PUBLIC KEY-----\n"}
        registry:
          enabled: true
          host: registry.heterocloud.mizuame.app
          username: admin
          authSecretName: heterocloud-registry-pull-auth
          passwordKey: password
          workloadPullSecretName: heterocloud-registry-pull
  destination:
    server: https://kubernetes.default.svc
    namespace: heterocloud-flash
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: flashservices.flash.heterocloud.io
      jsonPointers:
        - /spec/names/categories
        - /spec/versions/0/additionalPrinterColumns
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
