apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heterocloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: hetero-platform
  source:
    repoURL: https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud.git
    targetRevision: v0.1.78
    path: deploy/helm/heterocloud
    helm:
      releaseName: heterocloud
      valueFiles:
        - ../../environments/heteronet/values.yaml
      valuesObject:
        replicaCount: 3
        image:
          tag: "0.1.78@sha256:32699928177968fae16eff5e59839f0f506e9085563dded61b2b74a8801666de"
        worker:
          replicaCount: 3
        ownerConsole:
          replicaCount: 3
          externalIPs:
            - 10.250.0.4
            - 10.250.0.5
            - 10.250.0.6
            - 10.250.0.10
            - 10.250.0.11
        hostAliases:
          - ip: "10.96.180.79"
            hostnames:
              - console.heteronetwork.internal
  destination:
    server: https://kubernetes.default.svc
    namespace: heterocloud
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
