apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heterocloud-flash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: hetero-platform
  source:
    repoURL: https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud-Flash.git
    targetRevision: master
    path: deploy/helm/heterocloud-flash
    helm:
      releaseName: heterocloud-flash
      values: |
        image:
          tag: 0.1.2
        providerAuth:
          publicKeysJson: |-
            {"heterocloud-provider-1":"-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAs9HXnx9AwepDSdl/w+k2tAYieW3aU8PhlJoQBAFo9X4=\n-----END PUBLIC KEY-----\n"}
  destination:
    server: https://kubernetes.default.svc
    namespace: heterocloud-flash
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
