apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prerequisites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: hetero-platform
  source:
    repoURL: https://github.com/IPA-CyberLab/IPA-RS-HeteroNetwork.git
    targetRevision: master
    path: deploy/gitops/longhorn-prerequisites
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
