apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-syouyu-local
  labels:
    app.kubernetes.io/name: longhorn-syouyu-local
    app.kubernetes.io/part-of: heterocloud-syouyu
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: strict-local
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
