apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: heterocloud-edge
  namespace: heterocloud-edge
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 5
        pod:
          nodeSelector:
            networking.heteronetwork.io/public-ingress: "true"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "2"
              memory: 1Gi
      envoyPDB:
        minAvailable: 3
      envoyService:
        type: LoadBalancer
        loadBalancerClass: heteronetwork.io/public
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster
        loadBalancerSourceRanges:
          - 163.220.236.45/32
          - 163.220.236.51/32
          - 163.220.236.52/32
          - 163.220.236.53/32
          - 163.220.236.61/32
        annotations:
          networking.heteronetwork.io/traffic-mode: forwarded
          networking.heteronetwork.io/ingress-replicas: "5"
