apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: heterocloud-edge
  namespace: heterocloud-edge
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 5
        pod:
          nodeSelector:
            networking.heteronetwork.io/public-ingress: "true"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: envoy
                        gateway.envoyproxy.io/owning-gateway-name: heterocloud-edge
                    topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
                  gateway.envoyproxy.io/owning-gateway-name: heterocloud-edge
        container:
          resources:
              requests:
                cpu: 25m
                memory: 32Mi
            limits:
              cpu: "2"
              memory: 1Gi
      envoyPDB:
        minAvailable: 3
      envoyService:
        type: LoadBalancer
        loadBalancerClass: heteronetwork.io/public
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Cluster
        loadBalancerSourceRanges:
          - 163.220.236.51/32
          - 163.220.236.52/32
          - 163.220.236.53/32
          - 163.220.236.61/32
        annotations:
          networking.heteronetwork.io/traffic-mode: forwarded
          networking.heteronetwork.io/ingress-replicas: "5"
