apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: flow-abuse-limit
  namespace: heterocloud-flow
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: flow-public
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: flow-health
  rateLimit:
    global:
      rules:
        - clientSelectors:
            - sourceCIDR:
                type: Distinct
                value: 0.0.0.0/0
                invert: false
          limit:
            requests: 200
            unit: Second
          shared: true
        - clientSelectors:
            - sourceCIDR:
                type: Distinct
                value: ::/0
                invert: false
          limit:
            requests: 200
            unit: Second
          shared: true
