apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flow-public
  namespace: heterocloud-flow
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: heterocloud-edge
      namespace: heterocloud-edge
      sectionName: http
  hostnames:
    - flow.heterocloud.mizuame.app
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /rtc
      backendRefs:
        - group: ""
          kind: Service
          name: heterocloud-flow-livekit-signal
          port: 7880
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /v1/signal
      backendRefs:
        - group: ""
          kind: Service
          name: heterocloud-flow-signaling
          port: 8082
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: heterocloud-flow-api
          port: 8080
          weight: 1
