apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-primary-proxy.yaml
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - client-traffic-policy.yaml
  - backend-traffic-policy.yaml
  - heterocloud-backend.yaml
  - heterocloud-route.yaml
  - heterocloud-health-route.yaml
  - flow-route.yaml
  - flow-health-route.yaml
