apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: envoy-rate-limit-redis-proxy
    namespace: envoy-gateway-system
    files:
      - haproxy.cfg=haproxy.cfg
resources:
  - gatewayclass.yaml
  - envoyproxy.yaml
  - heterocloud-edge-proxy-service.yaml
  - gateway.yaml
  - client-traffic-policy.yaml
  - backend-traffic-policy.yaml
  - flow-backend-traffic-policy.yaml
  - redis-primary-proxy.yaml
  - heterocloud-backend.yaml
  - heterocloud-route.yaml
  - heterocloud-health-route.yaml
  - flow-route.yaml
  - flow-health-route.yaml
  - rate-limit-patch-policy.yaml
  - ratelimit-metrics-service.yaml
