apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: openbao-vpn
  namespace: openbao
spec:
  gatewayClassName: openbao-vpn
  listeners:
    - name: http
      protocol: HTTP
      port: 18083
      allowedRoutes:
        namespaces:
          from: Same
