apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: custom-domain-controller
    namespace: heterocloud-custom-domains
    files: [controller.py, site.json]
resources:
  - infrastructure.yaml
