services:
  agent:
    environment:
      - HETERONETWORK_DOCKER_API_CA_CERT_PATH=/run/heteronetwork/docker-api-ca.crt
    volumes:
      - type: bind
        source: ${HETERONETWORK_DOCKER_API_CA_CERT_PATH_HOST:?set HETERONETWORK_DOCKER_API_CA_CERT_PATH_HOST}
        target: /run/heteronetwork/docker-api-ca.crt
        read_only: true
        bind:
          create_host_path: false
