services:
  agent:
    environment:
      HETERONETWORK_DOCKER_DISCOVER_NETWORKS: "true"
      HETERONETWORK_DOCKER_CONTAINER_CIDRS: !reset null
      HETERONETWORK_DOCKER_NETWORKS: ${HETERONETWORK_ROOTLESS_DOCKER_NETWORK_A:?set HETERONETWORK_ROOTLESS_DOCKER_NETWORK_A}

  agent-b:
    environment:
      HETERONETWORK_DOCKER_DISCOVER_NETWORKS: "true"
      HETERONETWORK_DOCKER_CONTAINER_CIDRS: !reset null
      HETERONETWORK_DOCKER_NETWORKS: ${HETERONETWORK_ROOTLESS_DOCKER_NETWORK_B:?set HETERONETWORK_ROOTLESS_DOCKER_NETWORK_B}
