image:
  repository: ghcr.io/ipa-cyberlab/heteronetwork
  tag: ffc0b89
  pullPolicy: Never

agent:
  mode: host
  overlayDns:
    enabled: true
    records:
      console.heteronetwork.internal:
        - 10.250.0.5
        - 10.250.0.6
      grafana.heteronetwork.internal:
        - 10.250.0.4
        - 10.250.0.5
        - 10.250.0.6
      prometheus.heteronetwork.internal:
        - 10.250.0.4
        - 10.250.0.5
        - 10.250.0.6
      argocd.heteronetwork.internal:
        - 10.250.0.4
        - 10.250.0.5
        - 10.250.0.6

serviceExposure:
  enabled: false
