apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: identity-postgres
  namespace: hetero-dev-identity
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: dev-identity-postgres
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: dev-identity-postgres
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: keycloak
      ports:
        - {protocol: TCP, port: 5432}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 5432}
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: dev-identity-postgres
      ports:
        - {protocol: TCP, port: 5432}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - ipBlock: {cidr: 172.30.0.1/32}
        - ipBlock: {cidr: 10.251.0.1/32}
        - ipBlock: {cidr: 10.251.0.2/32}
        - ipBlock: {cidr: 10.251.0.3/32}
      ports:
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 6443}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: identity-operator
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - ipBlock: {cidr: 10.251.0.1/32}
        - ipBlock: {cidr: 10.251.0.2/32}
        - ipBlock: {cidr: 10.251.0.3/32}
      ports:
        - {protocol: TCP, port: 9443}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: hetero-dev-identity
          podSelector:
            matchLabels:
              cnpg.io/cluster: dev-identity-postgres
      ports:
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 5432}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - ipBlock: {cidr: 172.30.0.1/32}
        - ipBlock: {cidr: 10.251.0.1/32}
        - ipBlock: {cidr: 10.251.0.2/32}
        - ipBlock: {cidr: 10.251.0.3/32}
      ports:
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 6443}
