#!/usr/bin/env bash
set -euo pipefail

umask 077

readonly REALM="heteronetwork-customers"
readonly CUSTOMER_ROLE="heteronetwork-customer"
readonly ORG_ADMIN_ROLE="org-admin"
readonly CONSOLE_CLIENT_ID="heteronetwork-customer-console"
readonly API_CLIENT_ID="heteronetwork-customer-api"
readonly AUDIENCE_MAPPER_NAME="heteronetwork-customer-api-audience"
readonly ADMIN_USERNAME="customer-bootstrap-admin"
readonly LOCAL_SERVER_URL="http://127.0.0.1:28080"
readonly CONFIG_PATH="/etc/heteronetwork/customer-keycloak/customer-keycloak.env"
readonly ADMIN_PASSWORD_PATH="/etc/heteronetwork/customer-keycloak/secrets/bootstrap-admin.password"
readonly DEFAULT_KCADM_PATH="/opt/heteronetwork/customer-keycloak/bin/kcadm.sh"
readonly MAX_CONFIG_BYTES="65536"
readonly MAX_SECRET_BYTES="4096"
readonly -a FORBIDDEN_OPERATOR_ROLES=(
  heteronetwork-admin
  heteronetwork-operator
  heteronetwork-viewer
)

issuer_url="${HETERONETWORK_CUSTOMER_KEYCLOAK_ISSUER_URL:-}"
redirect_uris_csv="${HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_REDIRECT_URIS:-}"
web_origins_csv="${HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_WEB_ORIGINS:-}"
kcadm_path="${HETERONETWORK_CUSTOMER_KEYCLOAK_KCADM_PATH:-$DEFAULT_KCADM_PATH}"
kcadm_config=""

usage() {
  cat <<'EOF'
Usage: customer-keycloak-bootstrap.sh COMMAND

Commands:
  apply       Idempotently reconcile the customer realm, roles, and clients
  validate    Validate the live customer realm without changing it
  render      Render the non-secret desired realm state as JSON
  self-test   Validate the rendered realm contract without a live Keycloak

The apply and validate commands read the root-only installed configuration at
/etc/heteronetwork/customer-keycloak/customer-keycloak.env.
EOF
}

die() {
  printf 'customer-keycloak-bootstrap: error: %s\n' "$*" >&2
  exit 1
}

require_root() {
  [[ "$(id -u)" == "0" ]] || die "this command must run as root"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 \
    || die "required command is unavailable: $1"
}

secure_root_file() {
  local path="$1" maximum_size="$2"
  [[ "$path" == /* && -f "$path" && ! -L "$path" ]] || return 1
  local uid links mode size
  read -r uid links mode size < <(stat -c '%u %h %a %s' -- "$path") \
    || return 1
  [[ "$uid" == "0" && "$links" == "1" && "$mode" =~ ^[0-7]{3,4}$ ]] \
    || return 1
  (( (8#$mode & 0400) != 0 && (8#$mode & 0077) == 0 )) || return 1
  ((10#$size > 0 && 10#$size <= maximum_size))
}

load_installed_config() {
  secure_root_file "$CONFIG_PATH" "$MAX_CONFIG_BYTES" \
    || die "installed customer Keycloak configuration is missing or unsafe"

  unset \
    HETERONETWORK_CUSTOMER_KEYCLOAK_ISSUER_URL \
    HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_REDIRECT_URIS \
    HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_WEB_ORIGINS
  # This file is generated by customer-keycloak-node.sh and is root-only.
  # shellcheck disable=SC1090
  source "$CONFIG_PATH"

  issuer_url="${HETERONETWORK_CUSTOMER_KEYCLOAK_ISSUER_URL:-}"
  redirect_uris_csv="${HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_REDIRECT_URIS:-}"
  web_origins_csv="${HETERONETWORK_CUSTOMER_KEYCLOAK_CONSOLE_WEB_ORIGINS:-}"
}

validate_render_inputs() {
  [[ "$issuer_url" =~ ^https://[^/[:space:]]+/realms/${REALM}$ ]] \
    || die "customer issuer must be HTTPS and end in /realms/$REALM"
  [[ -n "$redirect_uris_csv" && "$redirect_uris_csv" != *[[:space:]]* ]] \
    || die "at least one whitespace-free console redirect URI is required"
  [[ -n "$web_origins_csv" && "$web_origins_csv" != *[[:space:]]* ]] \
    || die "at least one whitespace-free console web origin is required"
}

read_admin_password() {
  secure_root_file "$ADMIN_PASSWORD_PATH" "$MAX_SECRET_BYTES" \
    || die "bootstrap admin password is missing or unsafe"
  local password
  password="$(<"$ADMIN_PASSWORD_PATH")"
  [[ "$password" =~ ^[a-f0-9]{64}$ ]] \
    || die "bootstrap admin password has an invalid format"
  printf '%s' "$password"
}

render_realm() {
  jq -n \
    --arg realm "$REALM" \
    '{
      realm: $realm,
      displayName: "HeteroNetwork Customer Identity",
      enabled: true,
      sslRequired: "external",
      registrationAllowed: false,
      registrationEmailAsUsername: false,
      loginWithEmailAllowed: true,
      duplicateEmailsAllowed: false,
      resetPasswordAllowed: true,
      editUsernameAllowed: false,
      rememberMe: true,
      verifyEmail: true,
      bruteForceProtected: true,
      permanentLockout: false,
      failureFactor: 5,
      waitIncrementSeconds: 60,
      maxFailureWaitSeconds: 900,
      maxDeltaTimeSeconds: 43200
    }'
}

render_console_client() {
  jq -n \
    --arg client_id "$CONSOLE_CLIENT_ID" \
    --arg redirects "$redirect_uris_csv" \
    --arg origins "$web_origins_csv" \
    '{
      clientId: $client_id,
      name: "HeteroNetwork Customer Console",
      description: "Public PKCE client for customer resource management",
      enabled: true,
      protocol: "openid-connect",
      publicClient: true,
      bearerOnly: false,
      standardFlowEnabled: true,
      implicitFlowEnabled: false,
      directAccessGrantsEnabled: false,
      serviceAccountsEnabled: false,
      frontchannelLogout: true,
      fullScopeAllowed: false,
      redirectUris: ($redirects | split(",")),
      webOrigins: ($origins | split(",")),
      defaultClientScopes: ["web-origins", "acr", "profile", "roles", "email"],
      optionalClientScopes: ["address", "phone", "offline_access", "microprofile-jwt"],
      attributes: {
        "pkce.code.challenge.method": "S256",
        "oauth2.device.authorization.grant.enabled": "false",
        "oidc.ciba.grant.enabled": "false"
      }
    }'
}

render_api_client() {
  jq -n \
    --arg client_id "$API_CLIENT_ID" \
    '{
      clientId: $client_id,
      name: "HeteroNetwork Customer Resource API",
      description: "Bearer-only audience for public customer resource APIs",
      enabled: true,
      protocol: "openid-connect",
      publicClient: false,
      bearerOnly: true,
      standardFlowEnabled: false,
      implicitFlowEnabled: false,
      directAccessGrantsEnabled: false,
      serviceAccountsEnabled: false,
      fullScopeAllowed: false
    }'
}

render_audience_mapper() {
  jq -n \
    --arg name "$AUDIENCE_MAPPER_NAME" \
    --arg audience "$API_CLIENT_ID" \
    '{
      name: $name,
      protocol: "openid-connect",
      protocolMapper: "oidc-audience-mapper",
      consentRequired: false,
      config: {
        "included.client.audience": $audience,
        "id.token.claim": "false",
        "access.token.claim": "true",
        "userinfo.token.claim": "false",
        "introspection.token.claim": "true"
      }
    }'
}

render_desired_state() {
  validate_render_inputs
  jq -n \
    --arg issuer "$issuer_url" \
    --arg customer_role "$CUSTOMER_ROLE" \
    --arg org_admin_role "$ORG_ADMIN_ROLE" \
    --arg console_client_id "$CONSOLE_CLIENT_ID" \
    --arg api_client_id "$API_CLIENT_ID" \
    --argjson realm "$(render_realm)" \
    --argjson console_client "$(render_console_client)" \
    --argjson api_client "$(render_api_client)" \
    --argjson audience_mapper "$(render_audience_mapper)" \
    '{
      issuer: $issuer,
      realm: $realm,
      roles: [
        {
          name: $customer_role,
          description: "Required baseline role for authenticated customer application access"
        },
        {
          name: $org_admin_role,
          description: "May administer an organization only after application-level membership checks"
        }
      ],
      defaultRoles: [$customer_role],
      clients: [$console_client, $api_client],
      protocolMappers: [$audience_mapper],
      tokenContract: {
        authorizedParty: $console_client_id,
        audience: $api_client_id,
        requiredApplicationRole: $customer_role,
        organizationModifierRole: $org_admin_role
      }
    }'
}

cleanup() {
  if [[ -n "$kcadm_config" ]]; then
    rm -f -- "$kcadm_config"
  fi
}
trap cleanup EXIT HUP INT TERM

kc() {
  "$kcadm_path" "$@" --config "$kcadm_config"
}

kc_json() {
  local method="$1" path="$2" body="$3"
  printf '%s' "$body" \
    | "$kcadm_path" "$method" "$path" -r "$REALM" -f - \
      --config "$kcadm_config"
}

kc_global_json() {
  local method="$1" path="$2" body="$3"
  printf '%s' "$body" \
    | "$kcadm_path" "$method" "$path" -f - --config "$kcadm_config"
}

wait_until_ready() {
  local attempt
  for ((attempt = 1; attempt <= 60; attempt++)); do
    if curl --fail --silent --show-error \
      --connect-timeout 1 --max-time 2 \
      "$LOCAL_SERVER_URL/realms/master/.well-known/openid-configuration" \
      >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done
  die "local customer Keycloak did not become ready within 120 seconds"
}

login_admin() {
  local admin_password
  kcadm_config="$(mktemp /tmp/heteronetwork-customer-kcadm.XXXXXX)"
  chmod 0600 "$kcadm_config"
  admin_password="$(read_admin_password)"
  KC_CLI_PASSWORD="$admin_password" "$kcadm_path" config credentials \
    --config "$kcadm_config" \
    --server "$LOCAL_SERVER_URL" \
    --realm master \
    --user "$ADMIN_USERNAME" >/dev/null
  unset admin_password
}

ensure_realm() {
  local realms count desired
  desired="$(render_realm)"
  realms="$(kc get realms --fields realm)"
  count="$(jq --arg realm "$REALM" \
    '[.[] | select(.realm == $realm)] | length' <<<"$realms")"
  if ((count == 0)); then
    kc_global_json create realms "$desired" >/dev/null
  elif ((count == 1)); then
    kc_global_json update "realms/$REALM" "$desired" >/dev/null
  else
    die "multiple realms unexpectedly use the name $REALM"
  fi
}

ensure_role() {
  local role_name="$1" description="$2"
  local roles count desired
  roles="$(kc get roles -r "$REALM")"
  count="$(jq --arg role "$role_name" \
    '[.[] | select(.name == $role)] | length' <<<"$roles")"
  desired="$(jq -n --arg name "$role_name" --arg description "$description" \
    '{name: $name, description: $description}')"
  if ((count == 0)); then
    kc_json create roles "$desired" >/dev/null
  elif ((count == 1)); then
    kc_json update "roles/$role_name" "$desired" >/dev/null
  else
    die "realm role is duplicated: $role_name"
  fi
}

reject_operator_roles() {
  local roles forbidden
  roles="$(kc get roles -r "$REALM")"
  for forbidden in "${FORBIDDEN_OPERATOR_ROLES[@]}"; do
    if jq -e --arg role "$forbidden" '.[] | select(.name == $role)' \
      >/dev/null <<<"$roles"; then
      die "operator role $forbidden must not exist in the customer realm"
    fi
  done
}

ensure_role_composite() {
  local parent_name="$1" child_name="$2"
  local parent child composites parent_id representation
  parent="$(kc get "roles/$parent_name" -r "$REALM")"
  child="$(kc get "roles/$child_name" -r "$REALM")"
  parent_id="$(jq -er '.id | select(type == "string" and length > 0)' \
    <<<"$parent")"
  composites="$(kc get "roles-by-id/$parent_id/composites" -r "$REALM")"
  if ! jq -e --arg role "$child_name" '.[] | select(.name == $role)' \
    >/dev/null <<<"$composites"; then
    representation="$(jq '[{id, name, composite, clientRole, containerId}]' \
      <<<"$child")"
    kc_json create "roles-by-id/$parent_id/composites" \
      "$representation" >/dev/null
  fi
}

remove_role_composite_if_present() {
  local parent_name="$1" child_name="$2"
  local parent parent_id composites
  parent="$(kc get "roles/$parent_name" -r "$REALM")"
  parent_id="$(jq -er '.id' <<<"$parent")"
  composites="$(kc get "roles-by-id/$parent_id/composites" -r "$REALM")"
  if jq -e --arg role "$child_name" '.[] | select(.name == $role)' \
    >/dev/null <<<"$composites"; then
    kc remove-roles \
      --rname "$parent_name" \
      --rolename "$child_name" \
      -r "$REALM" >/dev/null
  fi
}

client_uuid() {
  local client_id="$1" clients count
  clients="$(kc get clients -r "$REALM" -q "clientId=$client_id")"
  count="$(jq --arg client_id "$client_id" \
    '[.[] | select(.clientId == $client_id)] | length' <<<"$clients")"
  ((count == 1)) || die "expected exactly one client named $client_id"
  jq -er --arg client_id "$client_id" \
    '.[] | select(.clientId == $client_id) | .id' <<<"$clients"
}

ensure_client() {
  local client_id="$1" desired="$2"
  local clients count uuid
  clients="$(kc get clients -r "$REALM" -q "clientId=$client_id")"
  count="$(jq --arg client_id "$client_id" \
    '[.[] | select(.clientId == $client_id)] | length' <<<"$clients")"
  if ((count == 0)); then
    kc_json create clients "$desired" >/dev/null
  elif ((count == 1)); then
    uuid="$(jq -er --arg client_id "$client_id" \
      '.[] | select(.clientId == $client_id) | .id' <<<"$clients")"
    kc_json update "clients/$uuid" "$desired" >/dev/null
  else
    die "client ID is duplicated: $client_id"
  fi
  client_uuid "$client_id" >/dev/null
}

role_representation() {
  local role_name="$1" roles
  roles="$(kc get roles -r "$REALM")"
  jq -ec --arg role "$role_name" \
    '[.[] | select(.name == $role) |
      {id, name, composite, clientRole, containerId}] |
      if length == 1 then . else error("missing or duplicate role") end' \
    <<<"$roles"
}

ensure_client_scope_role() {
  local client_id="$1" role_name="$2"
  local uuid current representation
  uuid="$(client_uuid "$client_id")"
  current="$(kc get "clients/$uuid/scope-mappings/realm" -r "$REALM")"
  if ! jq -e --arg role "$role_name" '.[] | select(.name == $role)' \
    >/dev/null <<<"$current"; then
    representation="$(role_representation "$role_name")"
    kc_json create "clients/$uuid/scope-mappings/realm" \
      "$representation" >/dev/null
  fi
}

ensure_audience_mapper() {
  local uuid mappers count mapper_id desired
  uuid="$(client_uuid "$CONSOLE_CLIENT_ID")"
  desired="$(render_audience_mapper)"
  mappers="$(kc get "clients/$uuid/protocol-mappers/models" -r "$REALM")"
  count="$(jq --arg name "$AUDIENCE_MAPPER_NAME" \
    '[.[] | select(.name == $name)] | length' <<<"$mappers")"
  if ((count == 0)); then
    kc_json create "clients/$uuid/protocol-mappers/models" "$desired" >/dev/null
  elif ((count == 1)); then
    mapper_id="$(jq -er --arg name "$AUDIENCE_MAPPER_NAME" \
      '.[] | select(.name == $name) | .id' <<<"$mappers")"
    kc_json update "clients/$uuid/protocol-mappers/models/$mapper_id" \
      "$desired" >/dev/null
  else
    die "audience mapper is duplicated: $AUDIENCE_MAPPER_NAME"
  fi
}

verify_role_composite() {
  local parent_name="$1" child_name="$2"
  local parent parent_id composites
  parent="$(kc get "roles/$parent_name" -r "$REALM")"
  parent_id="$(jq -er '.id' <<<"$parent")"
  composites="$(kc get "roles-by-id/$parent_id/composites" -r "$REALM")"
  jq -e --arg child "$child_name" \
    '.[] | select(.name == $child and .clientRole == false)' \
    >/dev/null <<<"$composites" \
    || die "$parent_name does not include $child_name"
}

verify_role_has_no_composites() {
  local role_name="$1" role role_id composites
  role="$(kc get "roles/$role_name" -r "$REALM")"
  role_id="$(jq -er '.id' <<<"$role")"
  composites="$(kc get "roles-by-id/$role_id/composites" -r "$REALM")"
  jq -e 'length == 0' >/dev/null <<<"$composites" \
    || die "$role_name must not inherit global application authorization"
}

verify_client() {
  local client_id="$1" expected_kind="$2"
  local uuid client
  uuid="$(client_uuid "$client_id")"
  client="$(kc get "clients/$uuid" -r "$REALM")"
  if [[ "$expected_kind" == "console" ]]; then
    jq -e \
      --arg client_id "$CONSOLE_CLIENT_ID" \
      --arg redirects "$redirect_uris_csv" \
      --arg origins "$web_origins_csv" '
        .clientId == $client_id
        and .enabled == true
        and .protocol == "openid-connect"
        and .publicClient == true
        and .bearerOnly == false
        and .standardFlowEnabled == true
        and .implicitFlowEnabled == false
        and .directAccessGrantsEnabled == false
        and .serviceAccountsEnabled == false
        and .fullScopeAllowed == false
        and .redirectUris == ($redirects | split(","))
        and .webOrigins == ($origins | split(","))
        and .attributes["pkce.code.challenge.method"] == "S256"
      ' >/dev/null <<<"$client" \
      || die "customer console client does not match the required PKCE contract"
  else
    jq -e --arg client_id "$API_CLIENT_ID" '
      .clientId == $client_id
      and .enabled == true
      and .protocol == "openid-connect"
      and .publicClient == false
      and .bearerOnly == true
      and .standardFlowEnabled == false
      and .directAccessGrantsEnabled == false
      and .serviceAccountsEnabled == false
      and .fullScopeAllowed == false
    ' >/dev/null <<<"$client" \
      || die "customer API client does not match the bearer-only contract"
  fi
}

verify_scope_roles() {
  local uuid mappings role forbidden
  uuid="$(client_uuid "$CONSOLE_CLIENT_ID")"
  mappings="$(kc get "clients/$uuid/scope-mappings/realm" -r "$REALM")"
  for role in "$CUSTOMER_ROLE" "$ORG_ADMIN_ROLE"; do
    jq -e --arg role "$role" '.[] | select(.name == $role)' \
      >/dev/null <<<"$mappings" \
      || die "console client is missing realm role scope $role"
  done
  for forbidden in "${FORBIDDEN_OPERATOR_ROLES[@]}"; do
    if jq -e --arg role "$forbidden" '.[] | select(.name == $role)' \
      >/dev/null <<<"$mappings"; then
      die "console client must not receive operator role scope $forbidden"
    fi
  done
}

verify_audience_mapper() {
  local uuid mappers
  uuid="$(client_uuid "$CONSOLE_CLIENT_ID")"
  mappers="$(kc get "clients/$uuid/protocol-mappers/models" -r "$REALM")"
  jq -e \
    --arg name "$AUDIENCE_MAPPER_NAME" \
    --arg audience "$API_CLIENT_ID" '
      [.[] | select(
        .name == $name
        and .protocolMapper == "oidc-audience-mapper"
        and .config["included.client.audience"] == $audience
        and .config["access.token.claim"] == "true"
        and .config["id.token.claim"] == "false"
      )] | length == 1
    ' >/dev/null <<<"$mappers" \
    || die "customer API audience mapper is missing or invalid"
}

verify_discovery() {
  local discovery
  discovery="$(curl --fail --silent --show-error \
    --connect-timeout 2 --max-time 5 --max-filesize 1048576 \
    "$LOCAL_SERVER_URL/realms/$REALM/.well-known/openid-configuration")"
  jq -e --arg issuer "$issuer_url" \
    '.issuer == $issuer and .authorization_endpoint == ($issuer + "/protocol/openid-connect/auth")' \
    >/dev/null <<<"$discovery" \
    || die "local discovery document does not advertise the configured public issuer"
}

verify_configuration() {
  local realm roles default_role
  realm="$(kc get "realms/$REALM")"
  jq -e \
    --arg realm "$REALM" '
      .realm == $realm
      and .enabled == true
      and .sslRequired == "external"
      and .registrationAllowed == false
      and .verifyEmail == true
      and .bruteForceProtected == true
    ' >/dev/null <<<"$realm" \
    || die "customer realm does not match the required security contract"

  roles="$(kc get roles -r "$REALM")"
  jq -e --arg customer "$CUSTOMER_ROLE" --arg org_admin "$ORG_ADMIN_ROLE" '
    ([.[] | select(.name == $customer and .clientRole == false)] | length == 1)
    and ([.[] | select(.name == $org_admin and .clientRole == false)] | length == 1)
  ' >/dev/null <<<"$roles" \
    || die "customer resource-management roles are missing"
  reject_operator_roles

  default_role="default-roles-$REALM"
  verify_role_composite "$default_role" "$CUSTOMER_ROLE"
  verify_role_has_no_composites "$ORG_ADMIN_ROLE"
  verify_client "$CONSOLE_CLIENT_ID" console
  verify_client "$API_CLIENT_ID" api
  verify_scope_roles
  verify_audience_mapper
  verify_discovery
}

validate_runtime() {
  require_root
  require_command curl
  require_command jq
  load_installed_config
  validate_render_inputs
  [[ -x "$kcadm_path" ]] || die "kcadm is not executable: $kcadm_path"
  wait_until_ready
  login_admin
}

apply_configuration() {
  validate_runtime
  ensure_realm
  ensure_role "$CUSTOMER_ROLE" \
    "Required baseline role for authenticated customer application access"
  ensure_role "$ORG_ADMIN_ROLE" \
    "May administer an organization only after application-level membership checks"
  reject_operator_roles
  ensure_role_composite "default-roles-$REALM" "$CUSTOMER_ROLE"
  remove_role_composite_if_present "$ORG_ADMIN_ROLE" "$CUSTOMER_ROLE"
  verify_role_has_no_composites "$ORG_ADMIN_ROLE"
  ensure_client "$CONSOLE_CLIENT_ID" "$(render_console_client)"
  ensure_client "$API_CLIENT_ID" "$(render_api_client)"
  ensure_client_scope_role "$CONSOLE_CLIENT_ID" "$CUSTOMER_ROLE"
  ensure_client_scope_role "$CONSOLE_CLIENT_ID" "$ORG_ADMIN_ROLE"
  ensure_audience_mapper
  verify_configuration
  printf 'Customer Keycloak realm %s is reconciled.\n' "$REALM"
}

validate_live_configuration() {
  validate_runtime
  verify_configuration
  printf 'Customer Keycloak realm %s is valid.\n' "$REALM"
}

self_test() {
  local rendered
  require_command jq
  issuer_url="https://identity.example.test/realms/$REALM"
  redirect_uris_csv="https://console.example.test/cloud/callback"
  web_origins_csv="https://console.example.test"
  rendered="$(render_desired_state)"
  jq -e \
    --arg issuer "$issuer_url" \
    --arg realm "$REALM" \
    --arg customer "$CUSTOMER_ROLE" \
    --arg org_admin "$ORG_ADMIN_ROLE" \
    --arg console "$CONSOLE_CLIENT_ID" \
    --arg api "$API_CLIENT_ID" '
      .issuer == $issuer
      and .realm.realm == $realm
      and .realm.sslRequired == "external"
      and .realm.registrationAllowed == false
      and .defaultRoles == [$customer]
      and (.roles | map(.name) == [$customer, $org_admin])
      and (.roles[1] | has("composites") | not)
      and (.clients | map(.clientId) == [$console, $api])
      and .clients[0].publicClient == true
      and .clients[0].attributes["pkce.code.challenge.method"] == "S256"
      and .clients[1].bearerOnly == true
      and .protocolMappers[0].config["included.client.audience"] == $api
      and .tokenContract.authorizedParty == $console
      and .tokenContract.audience == $api
      and .tokenContract.requiredApplicationRole == $customer
      and .tokenContract.organizationModifierRole == $org_admin
    ' >/dev/null <<<"$rendered" \
    || die "rendered customer identity contract is invalid"
  printf 'Customer Keycloak bootstrap self-test passed.\n'
}

case "${1:-}" in
  apply)
    apply_configuration
    ;;
  validate)
    validate_live_configuration
    ;;
  render)
    render_desired_state
    ;;
  self-test)
    self_test
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
