import { build } from "esbuild";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const webuiDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(webuiDir, "..");
const vendorDir = path.join(webuiDir, "vendor");
const bundlePath = path.join(vendorDir, "mermaid.min.js");
const noticesPath = path.join(vendorDir, "mermaid.NOTICES.txt");

await mkdir(vendorDir, { recursive: true });

const result = await build({
  absWorkingDir: root,
  bundle: true,
  charset: "utf8",
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  entryPoints: [path.join(webuiDir, "mermaid-entry.js")],
  format: "iife",
  legalComments: "linked",
  logLevel: "info",
  metafile: true,
  minify: true,
  outfile: bundlePath,
  platform: "browser",
  target: ["es2020"],
});

await writeThirdPartyNotices(result.metafile);

async function writeThirdPartyNotices(metafile) {
  const packageRoots = new Set();
  for (const input of Object.keys(metafile.inputs)) {
    const packageRoot = await findPackageRoot(path.resolve(root, input));
    if (packageRoot) packageRoots.add(packageRoot);
  }

  const packages = [];
  for (const packageRoot of packageRoots) {
    const metadata = JSON.parse(await readFile(path.join(packageRoot, "package.json"), "utf8"));
    const entries = await readdir(packageRoot, { withFileTypes: true });
    const licenseFiles = entries
      .filter((entry) => entry.isFile() && /^(licen[cs]e|copying|notice)(\..*)?$/i.test(entry.name))
      .map((entry) => entry.name)
      .sort();
    const licenses = [];
    for (const filename of licenseFiles) {
      licenses.push({
        filename,
        text: normalizeText(await readFile(path.join(packageRoot, filename), "utf8")),
      });
    }
    packages.push({
      name: String(metadata.name || path.basename(packageRoot)),
      version: String(metadata.version || "unknown"),
      license: formatLicense(metadata.license),
      repository: formatRepository(metadata.repository),
      licenses,
    });
  }
  packages.sort((left, right) =>
    left.name.localeCompare(right.name) || left.version.localeCompare(right.version),
  );

  const sections = [
    "HeteroNetwork Web UI Mermaid bundle third-party notices",
    "",
    "Bundle: webui/vendor/mermaid.min.js",
    "Generated by: npm run build:webui-vendor",
    "Inputs are pinned by the repository package-lock.json.",
    "",
    "The following packages contributed code to the generated browser bundle.",
  ];
  for (const entry of packages) {
    sections.push(
      "",
      "=".repeat(80),
      `${entry.name} ${entry.version}`,
      `Declared license: ${entry.license}`,
    );
    if (entry.repository) sections.push(`Source: ${entry.repository}`);
    if (!entry.licenses.length) {
      sections.push("No standalone license file was included in this package archive.");
      continue;
    }
    for (const license of entry.licenses) {
      sections.push("", `--- ${license.filename} ---`, license.text);
    }
  }
  await writeFile(noticesPath, `${sections.join("\n").trimEnd()}\n`, "utf8");
}

async function findPackageRoot(inputPath) {
  const segments = path.relative(root, inputPath).split(path.sep);
  const nodeModulesIndex = segments.lastIndexOf("node_modules");
  if (nodeModulesIndex < 0 || !segments[nodeModulesIndex + 1]) return null;
  const scoped = segments[nodeModulesIndex + 1].startsWith("@");
  if (scoped && !segments[nodeModulesIndex + 2]) return null;
  const packageRoot = path.join(
    root,
    ...segments.slice(0, nodeModulesIndex + (scoped ? 3 : 2)),
  );
  try {
    await readFile(path.join(packageRoot, "package.json"), "utf8");
    return packageRoot;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  return null;
}

function formatLicense(license) {
  if (typeof license === "string" && license.trim()) return license.trim();
  if (license && typeof license.type === "string" && license.type.trim()) {
    return license.type.trim();
  }
  return "not declared";
}

function formatRepository(repository) {
  const value = typeof repository === "string" ? repository : repository && repository.url;
  return typeof value === "string"
    ? value.replace(/^git\+/, "").replace(/\.git$/, "")
    : "";
}

function normalizeText(value) {
  return String(value).replace(/\r\n?/g, "\n").trimEnd();
}
