apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hetero-platform
  namespace: argocd
spec:
  description: HeteroNetwork and HeteroCloud production workloads
  sourceRepos:
    - https://github.com/IPA-CyberLab/IPA-RS-HeteroNetwork.git
    - https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud.git
    - https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud-Flow.git
    - https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud-Flash.git
    - https://github.com/IPA-CyberLab/IPA-RS-HeteroCloud-Syouyu.git
    - docker.io/envoyproxy
    - https://charts.longhorn.io
    - https://charts.bitnami.com/bitnami
    - https://helm.goharbor.io
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: envoy-gateway-system
      server: https://kubernetes.default.svc
    - namespace: heterocloud-edge
      server: https://kubernetes.default.svc
    - namespace: heterocloud
      server: https://kubernetes.default.svc
    - namespace: heterocloud-flow
      server: https://kubernetes.default.svc
    - namespace: heterocloud-flash
      server: https://kubernetes.default.svc
    - namespace: heterocloud-flash-workloads
      server: https://kubernetes.default.svc
    - namespace: heterocloud-syouyu
      server: https://kubernetes.default.svc
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
    - namespace: heterocloud-registry
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
