apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: heterocloud-dns
configMapGenerator:
  - name: public-dns-quorum-runtime
    files:
      - controller.py
      - pool.json
resources:
  - workloads.yaml
